compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: auto
  gradient_clipping: 1.0
  train_batch_size: auto
  train_micro_batch_size_per_gpu: auto
  zero_optimization:
    stage: 2
    offload_optimizer:
      device: none
    offload_param:
      device: none
    stage3_gather_16bit_weights_on_model_save: false
  bf16:
    enabled: true
  fp16:
    enabled: false
  optimizer:
    type: AdamW
    params:
      lr: auto
      betas: auto
      eps: auto
      weight_decay: auto
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2  # H100 can handle 2 processes efficiently
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
