_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
                - 98
                - 105
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.0001
adam_weight_decay_text_encoder:
    value: 0.001
allow_tf32:
    value: false
cache_dir:
    value: null
caption_column:
    value: null
center_crop:
    value: false
checkpointing_steps:
    value: 1000
checkpoints_total_limit:
    value: null
class_data_dir:
    value: null
class_prompt:
    value: null
controlnet_pretrained_model_name_or_path:
    value: null
dataloader_num_workers:
    value: 0
dataroot:
    value: ../data/VITON-HD
dataset_config_name:
    value: null
dataset_name:
    value: null
dropout_prob:
    value: 0
fuse_lora:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: false
guidance_scale:
    value: 1
height:
    value: 768
hub_model_id:
    value: null
hub_token:
    value: null
image_column:
    value: image
insert_dino_hs:
    value: false
instance_data_dir:
    value: dog
instance_prompt:
    value: null
learning_rate:
    value: 2e-05
local_model_path:
    value: null
local_rank:
    value: 0
logging_dir:
    value: logs
logit_mean:
    value: 0
logit_std:
    value: 1
lora_layers:
    value: null
lora_rank:
    value: 8
lora_scale:
    value: 1
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 0
max_grad_norm:
    value: 1
max_sequence_length:
    value: 512
max_train_steps:
    value: 100000
mixed_precision:
    value: bf16
mode_scale:
    value: 1.29
num_class_images:
    value: 100
num_img:
    value: 1
num_inference_steps:
    value: 50
num_train_epochs:
    value: 138
num_validation_images:
    value: 4
optimizer:
    value: adamw
output_dir:
    value: trained-flux-inpaint
pretrained_inpaint_model_name_or_path:
    value: xiaozaa/flux1-fill-dev-diffusers
pretrained_lora_path:
    value: null
pretrained_model_name_or_path:
    value: black-forest-labs/FLUX.1-dev
prior_generation_precision:
    value: null
prior_loss_weight:
    value: 1
prodigy_beta3:
    value: null
prodigy_decouple:
    value: true
prodigy_safeguard_warmup:
    value: true
prodigy_use_bias_correction:
    value: true
push_to_hub:
    value: false
random_flip:
    value: false
repeats:
    value: 1
report_to:
    value: wandb
resolution:
    value: 512
resume_from_checkpoint:
    value: null
revision:
    value: null
sample_batch_size:
    value: 4
scale_lr:
    value: false
seed:
    value: 42
text_encoder_lr:
    value: 5e-06
train_base_model:
    value: true
train_batch_size:
    value: 1
train_data_list:
    value: train_pairs.txt
train_lora:
    value: false
train_text_encoder:
    value: false
train_verification_list:
    value: subtrain_1.txt
use_8bit_adam:
    value: true
use_extra_residual:
    value: false
use_extra_residual_concat:
    value: false
use_local_model:
    value: false
validation_data_list:
    value: subtest_1.txt
validation_epochs:
    value: 2500
validation_prompt:
    value: null
validation_steps:
    value: 500
variant:
    value: null
vit_path:
    value: openai/clip-vit-base-patch16
weighting_scheme:
    value: none
width:
    value: 576
with_prior_preservation:
    value: false
